name: Copy notebooks from source repos

on:
  workflow_dispatch:
    inputs:
      deployment_spec:
        required: false
        type: string
        description: "Spec file to be read for copying notebooks, must be valid input to copy.py"
        default: .github/deployment-configs/deploy-deberta.yaml
  pull_request:


jobs:
  tests:
    uses: .github/workflows/copy-from-repo.yml
    with:
      deployment_spec: ${{ inputs.deployment_spec }}